# Generated by Django 5.1.7 on 2025-03-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
